### ISSUE TITLE
make errors

### ISSUE THREAD

**Issue by v-yunbin** [alphacep/vosk-server#101]
`g++ -shared -o libkaldi-matrix.so -Wl,--as-needed  -Wl,-soname=libkaldi-matrix.so,--whole-archive kaldi-matrix.a -Wl,--no-whole-archive  -Wl,-rpath=/opt/kaldi/tools/openfst-1.8.0/lib -rdynamic -Wl,-rpath=/opt/kaldi/src/lib  ../base/libkaldi-base.so /opt/kaldi/tools/openfst-1.8.0/lib/libfst.so -L/opt/kaldi/tools/OpenBLAS/install/lib -l:libopenblas.a -l:libblas.a -l:liblapack.a -l:libf2c.a -lm -lpthread -ldl
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(fmt.c.o): relocation R_X86_64_PC32 against symbol `f__elist' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(sfe.c.o): relocation R_X86_64_PC32 against symbol `f__fmtbuf' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(wsfe.c.o): relocation R_X86_64_PC32 against symbol `f__cursor' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(sig_die.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(f77_aloc.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(close.c.o): relocation R_X86_64_PC32 against symbol `f__units' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(endfile.c.o): relocation R_X86_64_PC32 against symbol `f__units' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(err.c.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(open.c.o): relocation R_X86_64_PC32 against symbol `f__buflen' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(wrtfmt.c.o): relocation R_X86_64_PC32 against symbol `f__cursor' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a(wref.c.o): relocation R_X86_64_PC32 against symbol `f__scale' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[1]: *** [../makefiles/default_rules.mk:53: libkaldi-matrix.so] Error 1
make[1]: Leaving directory '/opt/kaldi/src/matrix'
make: *** [Makefile:136: matrix] Error 2
`

**Comment by nshmyrev** [comment]
What is that? Would you be able to provide some details?

**Comment by v-yunbin** [comment]
@nshmyrev thanks，i have solved it，add codes "set(CMAKE_POSITION_INDEPENDENT_CODE ON) " in the beginging of Cmake file

**Comment by nshmyrev** [comment]
Ok, great.

I think we have that change already

https://github.com/alphacep/clapack/commit/4be8cb76121e6bd4156cf59d8bdb07ab757d9844
