### ISSUE TITLE
[Typo] Typo on Dockerfile.vosk-unimrcp file

### ISSUE THREAD

**Issue by hungnvk54** [alphacep/vosk-server#106]
I think you have made a typo mistake on Line 60 of Dockerfile.vosk-unimrcp file.

https://github.com/alphacep/vosk-server/blob/1461abc592855dceb436ca8538d7766b0a877216/docker/Dockerfile.vosk-unimrcp#L60

**Comment by nshmyrev** [comment]
Fixed now, thank you!
