### ISSUE TITLE
How can i specify chinese phrase list

### ISSUE THREAD

**Issue by waterLover** [alphacep/vosk-server#111]
I specify the phrase list [上, 下,左, 右], but I got this
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: '\\u4e0a'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: '\\u4e0b'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: '\\u5de6'
WARNING (VoskAPI:KaldiRecognizer():kaldi_recognizer.cc:89) Ignoring word missing in vocabulary: '\\u53f3'

However, I can get these words(上下左右) in result when I didn't specify the phrase list. 
so I suppose the vocabulary should includes these words already.
But why I still get these warning?
Dose anyone could help me?

**Comment by nshmyrev** [comment]
This should be fixed now, thanks for the report!
