### ISSUE TITLE
Loading rnnlm model: cannot load file /rnnlm/special_symbol_opts.conf

### ISSUE THREAD

**Issue by euxsun** [alphacep/vosk-server#113]
Error appears when using vosk docker: [alphacep/kaldi-vosk-server:latest](https://hub.docker.com/layers/alphacep/kaldi-vosk-server/latest/images/sha256-8b1a3efbe0284afe03caa7be444b24bb2a802878fe72957c9562ddb5163d08c9?context=explore) (version from 20 May 2021).
When initialize Kaldi on Russian language, downloaded from the Alphacephei Vosk models [vosk-model-ru-0.10.zip](https://alphacephei.com/vosk/models/vosk-model-ru-0.10.zip) an exception raised:

```
LOG (VoskAPI:ReadDataFiles():vosk/model.cc:273) Loading rnnlm model: cannot load file /rnnlm/special_symbol_opts.conf
```

In the folder `rnnlm` there is no this file, but `special_symbol_opts.txt` present. Changing it's extension doesn't solve the issue.

**Comment by nshmyrev** [comment]
You need to download file again https://alphacephei.com/vosk/models/vosk-model-ru-0.10.zip, it was recently updated

**Comment by nshmyrev** [comment]
I suppose this is solved.
