### ISSUE TITLE
model size and location

### ISSUE THREAD

**Issue by MikeyBeez** [alphacep/vosk-server#115]
Which model is being used?  Can I use a larger model?  How would I do that?  Cheers.  Thanks.

**Comment by MikeyBeez** [comment]
I'd like to use the best/largest model for the most accurate results.  How do I do that?

**Comment by nshmyrev** [comment]
You download the model and unpack in the same folder as the server. Then run ./asr_server.py

**Comment by MikeyBeez** [comment]
So I found the model by looking in the container.  It's the Aspire model, which appears to be your best model.  Thanks.

**Comment by nshmyrev** [comment]
> It's the Aspire model, which appears to be your best model. 

aspire model is not the best

**Comment by MikeyBeez** [comment]
> ./asr_server.py

I think that means go into the container with docker exec -it ,container_id. then cd /opt.  Then download and unzip the model.  It should overwrite vosk-model-en.  But then it will not persist, unless I mount that as a volume.  Otherwise, I could do all this in my dockerfile.  Sorry for being so slow about this.  I'm new to Docker.

**Comment by MikeyBeez** [comment]
If aspire isn't the best, which is?  These are my choices:  https://alphacephei.com/vosk/models

**Comment by MikeyBeez** [comment]
I found these too:  http://kaldi-asr.org/models/m13

**Comment by nshmyrev** [comment]
> But then it will not persist, unless I mount that as a volume.

You can simply mount your model as a volume instead of /opt/vosk-model-en. 

It is also easy to create your own container which inherits kaldi-en.

> If aspire isn't the best, which is?

There are numbers in the table.
