### ISSUE TITLE
problem with Setup Vosk Server

### ISSUE THREAD

**Issue by iProMC** [alphacep/vosk-server#116]
Hello, months ago I have tired a vosk-API but I have seen that the model file is not arcuate enough for me. so I want to try vosk-server so I can get arcuate speech recognition.

I have visited the website (https://alphacephei.com/vosk/server) and I have downloaded it and I got lost I don't know how to install it correctly if anyone can tell me how to install it correctly I will appreciate that

**Comment by nshmyrev** [comment]
1. Install docker
2. In command line run `docker run -d -p 2700:2700 alphacep/kaldi-en:latest`

Thats it

**Comment by iProMC** [comment]
ok, how does the vosk -server method works?

1-does the vosk-server create a model folder so I transferred to vosk-api??
2-do I need a GPU in order to do machine learning??

**Comment by nshmyrev** [comment]
> 1-does the vosk-server create a model folder so I transferred to vosk-api??

Model is included into docker image

> 2-do I need a GPU in order to do machine learning??

No

**Comment by iProMC** [comment]
is the arcuate of vosk-server is higher than vosk-api?

**Comment by nshmyrev** [comment]
No, it is exactly same. Same code and same models.

**Comment by nshmyrev** [comment]
I suppose this one is solved
