### ISSUE TITLE
Giving telephony audio file to vosk-server

### ISSUE THREAD

**Issue by rose768** [alphacep/vosk-server#121]
Hi,
I run vosk-server demo with WebRTC protocol at http://0.0.0.0:2700/. It works well with microphone.
How can I give a telephony audio file to the demo at http://0.0.0.0:2700/  and see the transcript?

**Comment by nshmyrev** [comment]
Same way? It should work, try it. You might just configure sample rate on the server side.

**Comment by nshmyrev** [comment]
Feel free to reopen if you have further questions
