### ISSUE TITLE
test_microphone.py need to be updated ?

### ISSUE THREAD

**Issue by ThierryH** [alphacep/vosk-server#144]
Hello , 
I've tested the Vosk server with the test_microphone.py.  And if i follow the doc , thing are not good. 
After looking a bit in the code , it seems that the python script send the stream using 8KHz data where the server ( latest version ) need to get 16Khz audio.  Changing the python code make the whole solution work like a charm :) 

Regards

**Comment by ThierryH** [comment]
I was testing the french docker , the issue does not occur with the english one.

**Comment by nshmyrev** [comment]
We introduced samplerate option in new test_microphone now. Thank you for the report.
