### ISSUE TITLE
Request for .lm files of vosk-model-ru-0.22

### ISSUE THREAD

**Issue by VidSim** [alphacep/vosk-server#152]
Would like to add some company names to new RU model, but we are missing language model files. How could we get them?

**Comment by nshmyrev** [comment]
You can contact us at contact@alphacephei.com

**Comment by nshmyrev** [comment]
Now published on https://alphacephei.com/vosk/lm:

https://alphacephei.com/vosk/models/vosk-model-ru-0.22-compile.zip
