### ISSUE TITLE
"Failed to create model" with the newest russian model.

### ISSUE THREAD

**Issue by chamoretto** [alphacep/vosk-server#153]
Hello. We have some troubles with the newest russian model. Previously we used august 2021 version of the model, now we decided to deploy additional instance of jitsi with ru and en models. The model version "en" is fine, but with the "ru" latest docker image we getting this error:
![image](https://user-images.githubusercontent.com/28485306/142874217-550048dc-1fb9-49c2-8977-7a93eb8e413b.png)

We have tested new model on both Ubuntu 20.04 (8 cores, 12 GB RAM) and Debian 10 (4 cores, 12GB RAM), both fails to launch the newest model with the error on the screenshot above.

**Comment by nshmyrev** [comment]
Try to add more RAM

**Comment by sskorol** [comment]
Or just remove `rnnlm` folder from the model, which should also drop the memory consumption.

**Comment by chamoretto** [comment]
> Try to add more RAM

We've added RAM, now it's 4 cores and 14 GB of RAM is enough per one instance, and the model is loaded, but the actual workload does not exceed 10 GB. It's kinda strange, but works now. Thank you!

Feel free to close this issue due to resolved problem, if you have no another advices.

**Comment by nshmyrev** [comment]
Same as #77
