### ISSUE TITLE
webrtc error

### ISSUE THREAD

**Issue by wizVR-zhangjun** [alphacep/vosk-server#159]
$ python asr_server_webrtc.py
(base) zhanggan@zhanggan-B460MDS3HV2:~/桌面/vosk-server-master/webrtc$ python asr_server_webrtc.py
ERROR (VoskAPI:Model():model.cc:122) Folder 'model' does not contain model files. Make sure you specified the model path properly in Model constructor. If you are not sure about relative path, use absolute path specification.
Traceback (most recent call last):
  File "asr_server_webrtc.py", line 26, in <module>
    model = Model(vosk_model_path)
  File "/home/zhanggan/.local/lib/python3.8/site-packages/vosk/__init__.py", line 29, in __init__
    raise Exception("Failed to create a model")
Exception: Failed to create a model
(base) zhanggan@zhanggan-B460MDS3HV2:~/桌面/vosk-server-master/webrtc$ 
@nshmyrev

**Comment by nshmyrev** [comment]
Same as #160
