### ISSUE TITLE
Webrtc reports an error when running on Windows

### ISSUE THREAD

**Issue by wizVR-zhangjun** [alphacep/vosk-server#160]
When I run ASR under Windows_ server_ webrtc. Py didn't make any mistakes. When I click the start button on the web page, the console has a problem. Is there any solution to this problem?
![image](https://user-images.githubusercontent.com/60952586/147453937-a3615500-ef86-4e59-89f5-f325705853c8.png)
@nshmyrev  Thank you

**Comment by nshmyrev** [comment]
> Is there any solution to this problem?

It says you need to upgrade pyOpenSSL

**Comment by wizVR-zhangjun** [comment]
> > Is there any solution to this problem?
> 
> It says you need to upgrade pyOpenSSL

![lQLPDhsAbA77WL7NBA_NB36wZWsAQGML0bwB0V1hOEAZAA_1918_1039](https://user-images.githubusercontent.com/60952586/147523456-744292eb-9f1a-4288-882c-f1201c1edad0.png)
The microphone is turned on and the console does not receive any messages

**Comment by SreeramGanji** [comment]
> > > Is there any solution to this problem?
> > 
> > 
> > It says you need to upgrade pyOpenSSL
> 
> ![lQLPDhsAbA77WL7NBA_NB36wZWsAQGML0bwB0V1hOEAZAA_1918_1039](https://user-images.githubusercontent.com/60952586/147523456-744292eb-9f1a-4288-882c-f1201c1edad0.png) The microphone is turned on and the console does not receive any messages

Hi!

I too am facing the same issue. Can you let me know if you are able to solve it ?

**Comment by wizVR-zhangjun** [comment]
> > > > Is there any solution to this problem?
> > > 
> > > 
> > > It says you need to upgrade pyOpenSSL
> > 
> > 
> > ![lQLPDhsAbA77WL7NBA_NB36wZWsAQGML0bwB0V1hOEAZAA_1918_1039](https://user-images.githubusercontent.com/60952586/147523456-744292eb-9f1a-4288-882c-f1201c1edad0.png) The microphone is turned on and the console does not receive any messages
> 
> Hi!
> 
> I too am facing the same issue. Can you let me know if you are able to solve it ?

I have been looking for the answer, but the result is not very ideal

**Comment by nshmyrev** [comment]
Also discussed in https://github.com/alphacep/vosk-server/pull/94

**Comment by wizVR-zhangjun** [comment]
> > > > Is there any solution to this problem?
> > > 
> > > 
> > > It says you need to upgrade pyOpenSSL
> > 
> > 
> > ![lQLPDhsAbA77WL7NBA_NB36wZWsAQGML0bwB0V1hOEAZAA_1918_1039](https://user-images.githubusercontent.com/60952586/147523456-744292eb-9f1a-4288-882c-f1201c1edad0.png) The microphone is turned on and the console does not receive any messages
> 
> Hi!
> 
> I too am facing the same issue. Can you let me know if you are able to solve it ?

![image](https://user-images.githubusercontent.com/60952586/147806286-d235ecc9-3035-462c-8e6a-2f5487f761e7.png)
![image](https://user-images.githubusercontent.com/60952586/147806313-6b6307aa-8cf1-4ec1-a52c-01344776ad6e.png)

I made some modifications here. According to the screenshot above, I can run correctly on windows

**Comment by Aljumaili85** [comment]
> When I run ASR under Windows_ server_ webrtc. Py didn't make any mistakes. When I click the start button on the web page, the console has a problem. Is there any solution to this problem? ![image](https://user-images.githubusercontent.com/60952586/147453937-a3615500-ef86-4e59-89f5-f325705853c8.png) @nshmyrev Thank you

upgrading pyOpenSSL doesn't resolve the problem, any suggestion?
