### ISSUE TITLE
webrtc  asr_server_webrtc.py  The expected results were not achieved

### ISSUE THREAD

**Issue by wizVR-zhangjun** [alphacep/vosk-server#162]
![image](https://user-images.githubusercontent.com/60952586/147731244-6101e108-78d5-4b46-a9c7-1dec8a0e4254.png)
As shown in the figure above__ run_ audio_ Xfer () has entered, but it is not always executed in the where loop. After five times of the where loop, it is not executed again, and the marked places are not printed, @nshmyrev  Please help me

**Comment by nshmyrev** [comment]
Already discussed in #160
