### ISSUE TITLE
The  use of Asterisk 

### ISSUE THREAD

**Issue by v-yunbin** [alphacep/vosk-server#173]
I follow the asterisk client instruction to install all dependence，set dialpan and sip config， when  I call 103 from 101,get follow meassage, When the phone was connected, it was hung up immediately.
` eagi.py: EAGI script started...
 eagi.py: Call answered from: 101 to 103
    -- <SIP/101-0000004d>AGI Script eagi.py completed, returning 0
    -- Executing [103@internal:3] Hangup("SIP/101-0000004d", "") in new stack
  == Spawn extension (internal, 103, 3) exited non-zero on 'SIP/101-0000004d'
`

**Comment by v-yunbin** [comment]
extensions.conf
```
exten => 200,1,Answer()
same = n,EAGI(eagi.py)
same = n,Hangup()
```
it seems  the  FD not  work.

**Comment by v-yunbin** [comment]
> extensions.conf
> 
> ```
> exten => 200,1,Answer()
> same = n,EAGI(eagi.py)
> same = n,Hangup()
> ```
> 
> it seems the FD not work.

I have debug  the problem，FD works. when run the function "process_chunk", the errors happend.

**Comment by nshmyrev** [comment]
What kind of error?

**Comment by v-yunbin** [comment]
> What kind of error?

sorry, its my error, i close it,  the codes no problem.

**Comment by v-yunbin** [comment]
Excuse me, @nshmyrev I know  that  using “FD = 3”， I can  get a channel  audio steam，do u know how  to obtain multi-channel speech streams respectively.
 “FD = 3” get left channel  audio steam, “FD = 4” get right channel  audio steam?
