### ISSUE TITLE
"Failed to create model" despite model dir being present

### ISSUE THREAD

**Issue by watermelon4468** [alphacep/vosk-server#174]
Hi
I've been trying to use vosk-server on my raspberry pi; I've cloned the repository and downloaded a model. I extracted the model into a folder called "model", in the same directory as the websocket file i'm trying to run: `asr_server.py` in the websocket/ folder. However, it keeps saying "failed to create model" and is giving this output:
![image](https://user-images.githubusercontent.com/76520109/160479510-adb9a88e-bc6f-4667-be66-c127619d262d.png)
Any help much appreciated,
Thank you very much

**Comment by nshmyrev** [comment]
Most likely it goes out of memory, big models are not suitable for RPI. You might try to delete rescore and rnnlm from the model, it might run then.

**Comment by watermelon4468** [comment]
Thank you, that appears to be working now :-)

**Comment by nshmyrev** [comment]
Same as #77
