### ISSUE TITLE
from unimrcp docker image undefined symbol: vosk_recognizer_set_nlsml

### ISSUE THREAD

**Issue by herbiel** [alphacep/vosk-server#176]
Failed to Load DSO: /usr/local/unimrcp/plugin/voskrecog.so: undefined symbol: vosk_recognizer_set_nlsml

**Comment by herbiel** [comment]
sorry,it's from the unimrcp dockerfile

**Comment by nshmyrev** [comment]
I've just pushed an updated image, everything should be fine there.

**Comment by nshmyrev** [comment]
I hope this issue is fixed. Let us know if you have other questions.
