### ISSUE TITLE
 alphacep/kaldi-ru:latest not working

### ISSUE THREAD

**Issue by nozzy177** [alphacep/vosk-server#177]
I want to load docker:
docker run -p 2700:2700 alphacep/kaldi-ru:latest

log:

LOG (VoskAPI:ReadDataFiles():model.cc:213) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG (VoskAPI:ReadDataFiles():model.cc:216) Silence phones 1:2:3:4:5:6:7:8:9:10
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.697269 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():model.cc:248) Loading i-vector extractor from /opt/vosk-model-ru/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():model.cc:279) Loading HCLG from /opt/vosk-model-ru/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():model.cc:294) Loading words from /opt/vosk-model-ru/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():model.cc:303) Loading winfo /opt/vosk-model-ru/model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():model.cc:310) Loading subtract G.fst model from /opt/vosk-model-ru/model/rescore/G.fst
LOG (VoskAPI:ReadDataFiles():model.cc:312) Loading CARPA model from /opt/vosk-model-ru/model/rescore/G.carpa
LOG (VoskAPI:ReadDataFiles():model.cc:318) Loading RNNLM model from /opt/vosk-model-ru/model/rnnlm/final.raw

At this step, the memory on my server (8GB) overflows and the docker does not load.
But english version of the docker (alphacep/kaldi-en:latest) loads fine and works.

**Comment by nshmyrev** [comment]
Same as #77, You need more memory (16Gb)
