### ISSUE TITLE
vosk build on Riscv platform

### ISSUE THREAD

**Issue by kush930** [alphacep/vosk-server#183]
Hi all,

I want to **build vosk-0.3.42 speech recognition on Riscv platform using pip3** , please anyone tell me the steps to build vosk on Riscv platform, I am **using python3 version-3.8.5 and pip3 version 20.0.2** .

**$ pip3 install vosk**

I am getting below error

**ERROR: Could not find a version that satisfies the requirement vosk (from versions: none)
ERROR: No matching distribution found for vosk**

T&R
Kush

T&R
Kush

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-api/issues/989

**Comment by kush930** [comment]
yes nshmyrev,
