### ISSUE TITLE
The docker can be only built with debian:10 but not 11

### ISSUE THREAD

**Issue by YunzhaoLu** [alphacep/vosk-server#184]
Hi, I am trying to build the docker image with the following docker file, but it always failed with "E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gdbm/libgdbm6_1.19-2_amd64.deb  Connection timed out [IP: 151.101.78.132 80]
E: Sub-process /usr/bin/dpkg returned an error code (1)".

[vosk-server](https://github.com/alphacep/vosk-server)/[docker](https://github.com/alphacep/vosk-server/tree/master/docker)/Dockerfile.kaldi-vosk-server

If I build the docker image with debian:10, it can be successfully built. The installed python is 3.7.3, but I want python version of 3.8 or 3.9.
Thank you.

**Comment by nshmyrev** [comment]
I can download that deb just fine. It might be some network issue. Just try again.
