### ISSUE TITLE
question/idea: docker models injection

### ISSUE THREAD

**Issue by codemeister64** [alphacep/vosk-server#187]
Hi! I have a question: 
why we are using several docker files for each language model? 

I think we could mount ```/opt/vosk-server/***/model``` folder, so we can move out models from docker container. 
Also we could introduce some env variable to specify custom model name instead of default one.

With this change docker containers will have smaller size and it eliminates need to rebuild container if I want to try different models (or my own).

What do you think? Or there are some cases that are covered by current approach?

**Comment by sskorol** [comment]
It's quite easy to do via [volumes](https://github.com/sskorol/vosk-api-gpu/blob/a5ec18e967148771741b963d8e2ade15f7e810c3/docker-compose.yml)

**Comment by nshmyrev** [comment]
You can bind model folder with -v even now. I've updated the docs about it.

https://alphacephei.com/vosk/server#usage
