### ISSUE TITLE
Is it possible to flush and get the final result quicker?

### ISSUE THREAD

**Issue by aj3423** [alphacep/vosk-server#199]
When test with some .wav file, send its content to docker "alphacep/kaldi-en" to get the result. The problem is that even the .wav duration is 0.7 second, it takes 2 seconds to get the final result.

And it takes 2.46 seconds with another file *test16k.wav*,  which has a duration of 8 seconds. (files attached)

Files with different duration have similar recognition time, so I guess the 2.x seconds is not cost by the recognition but by waiting for the further voice input. 

I tried to send the `{"eof" : 1}` right after the .wav data, but it changes nothing, my code looks like:
```golang
ws.WriteMessage(websocket.BinaryMessage, wav_binary) // send full .wav binary data to docker websocket
ws.WriteMessage(websocket.TextMessage, []byte(`{"eof" : 1}`))

_, msg, err := ws.ReadMessage() // <---- this takes 2+ seconds
check(err)
```

I want to write an application that when user press down space-key, it starts voice recognition, and stops when user release space-key. So when the key is released I want to send some signal to VOSK to tell it please stop waiting for further data and return the current result.

It it possible? Thanks.

Environment: Linux, Docker, GoLang
CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
[two_wav_file.zip](https://github.com/alphacep/vosk-server/files/9608406/two_wav_file.zip)

**Comment by nshmyrev** [comment]
Do you open a new connection for this short file of 0.7 second? There might be some initialization delays on start, we are working on them.

**Comment by aj3423** [comment]
I tried with a loop, when I press Enter, the file(0.7 sec) is sent to the same websocket connection, after the result comes back and the CPU goes down, I press Enter again. But each time takes 2+ seconds, code looks like:
```golang
for {
	console.ReadLine() // wait for Enter key

	c.WriteMessage(websocket.BinaryMessage, wav_binary)
	startTime := time.Now() // start time
	c.ReadMessage()
	fmt.Println("cost time", time.Since(startTime)) // endTime - startTime
}
```
And I found something strange, it takes about 2 seconds at the beginning, and increases slowly to 2.5 seconds, then suddenly goes back to 2 seconds, and again slowly increases to 2.5...

The output:

> cost time 2.107240386s  <---- slightly increases every time
> cost time 2.150806483s
> cost time 2.195205492s
> cost time 2.165041861s
> cost time 2.15906109s
> cost time 2.192868188s
> cost time 2.205444671s
> cost time 2.204596564s
> cost time 2.262786981s
> cost time 2.262085261s
> cost time 2.247334387s
> cost time 2.319574653s
> cost time 2.322887681s
> cost time 2.32494464s
> cost time 2.342035688s
> cost time 2.320160247s
> cost time 2.411576218s
> cost time 2.296371765s
> cost time 2.292653507s
> cost time 2.306706403s
> cost time 2.398048123s
> cost time 2.381953083s
> cost time 2.383488176s
> cost time 2.418880683s
> cost time 2.491025419s
> cost time 2.480065428s
> cost time 2.407760942s
> cost time 2.439044845s
> cost time 2.518405869s
> cost time 2.448134596s
> cost time 2.507141128s
> cost time 2.459280811s
> cost time 2.472698952s
> cost time 2.506513625s
> cost time 2.565051114s
> cost time 2.523880109s
> cost time 2.494999518s
> cost time 2.429409824s
> cost time 2.564455329s  <---- 2.56 here, next 2.1
> cost time 2.101728663s
> cost time 2.090588243s
> cost time 2.186388586s
> cost time 2.186052211s
> cost time 2.229697992s
> cost time 2.177035073s
> cost time 2.326669026s
> cost time 2.20159241s
> cost time 2.214988629s
> cost time 2.287041673s
> cost time 2.33072265s
> cost time 2.369703271s
> cost time 2.286018984s
> cost time 2.212637077s
> cost time 2.301985927s
> cost time 2.363377321s
> cost time 2.428361331s
> cost time 2.31104525s
> cost time 2.300519288s
> cost time 2.322921209s
> cost time 2.357747416s
> cost time 2.418997855s
> cost time 2.440369735s
> cost time 2.431108904s
> cost time 2.471907782s
> cost time 2.385840349s
> cost time 2.413532525s
> cost time 2.449118487s
> cost time 2.485857425s
> cost time 2.513138005s
> cost time 2.548427576s
> cost time 2.489148885s
> cost time 2.463726182s
> cost time 2.485083934s
> cost time 2.549396734s
> cost time 2.587447343s
> cost time 2.528120283s
> cost time 2.528516109s
> cost time 2.506699821s  <---- 2.5 again, next 2.02
> cost time 2.022089545s
> cost time 2.060613543s
> cost time 2.175181613s
> cost time 2.157324036s

dsfsaf
