### ISSUE TITLE
Custom model seems not working in docker

### ISSUE THREAD

**Issue by kundanashish** [alphacep/vosk-server#212]
I fine tuned en-in for random text. It is working fine when running directly in .net api check screenshot but not when I host it in docker passing custom model location
![image](https://user-images.githubusercontent.com/13413950/213924655-2a673c63-d59e-4b0d-8ba7-fa4f1f96c52a.png)

sample command for docker I used
sudo docker run -d -p 2700:2700 -v /opt/model:/opt/custommodel alphacep/kaldi-en-in:latest
![image](https://user-images.githubusercontent.com/13413950/213924745-b71a9899-69f3-42e8-a1c0-9399fbdd1022.png)

Please refer to this link for the model file and text on which it is fine tunned

https://graticare-my.sharepoint.com/:u:/p/kundan/EXCG_NiKRrxLuEHJaIu53w8Be5miIDV0JIZ-2ToLXWoLkQ?e=x44BSs

Please help

**Comment by nshmyrev** [comment]
What does not work exactly? You didn't describe the problem, what is the output you see?

You can remove -d from docker command to see the output.

**Comment by kundanashish** [comment]
sorry seems something missing at my end
thanks for guiding below is the error
![image](https://user-images.githubusercontent.com/13413950/213926317-52d2c41c-e538-4f05-8a8d-7448b7af0901.png)
but I have placed the files
![image](https://user-images.githubusercontent.com/13413950/213926332-97f108aa-c90f-4512-bb06-deeafb660aa0.png)

**Comment by nshmyrev** [comment]
You just need to figure proper option for path mapping. Not sure what is your host path, but probably you need  `-v /opt/vosk-something-else:/opt/vosk-model-en-in/model` instead of your current `/opt/model`

**Comment by kundanashish** [comment]
![image](https://user-images.githubusercontent.com/13413950/213927155-d4b35e4d-f2cd-4347-a2db-97d0f9c817db.png)
When I run it like this. it is not giving any error but accuracy is not good. Seems its still not using custom model.

Yes I am trying. Thanks for the guidance.

**Comment by kundanashish** [comment]
Hi @nshmyrev 
Yes you are right. My bad I passed the parameters interchangeably.
its working fine now.

Thanks again for the great help so quickly.
