### ISSUE TITLE
bSocket connection to 'ws://localhost:2700/' failed: 

### ISSUE THREAD

**Issue by ch930410** [alphacep/vosk-server#219]
D:\vosk-server>docker ps
CONTAINER ID   IMAGE                      COMMAND                  CREATED             STATUS             PORTS                             NAMES
1dfcba478d6e   alphacep/kaldi-en:latest   "python3 ./asr_serve…"   About an hour ago   Up About an hour   2700/tcp, 0.0.0.0:2700->270/tcp   modest_lalande

running D:\vosk-server\client-samples\javascript\index.html File; click listen button error.

for the first time studying this, please help to answer; thank you

**Comment by nshmyrev** [comment]
You need like 16Gb of memory, most likely docker has not enough memory to run the container

**Comment by ch930410** [comment]
I have 32Gb of memory, which is enough
