### ISSUE TITLE
can only recognize chinese, not english?

### ISSUE THREAD

**Issue by ch930410** [alphacep/vosk-server#220]
the wav file provided by the demo is recognized as chinese
filePath: D:\vosk-server\client-samples\javascript\index.html

![image](https://user-images.githubusercontent.com/28522577/234197603-0a4fe86f-9ef6-4a24-aa16-b8b58571922b.png)

**Comment by nshmyrev** [comment]
We can create multilingual models in the future, for now the models are focused on a single language. We might add some English words to the model though, but it needs extra work.

**Comment by ch930410** [comment]
hello, I need an English model. May I know where to obtain this model

**Comment by ch930410** [comment]
Found; [alphacep/kaldi-en](https://hub.docker.com/r/alphacep/kaldi-en) library
