### ISSUE TITLE
Why does transcription have a significant drop in quality while running over docker?

### ISSUE THREAD

**Issue by Deuos** [alphacep/vosk-server#227]
While using the small english model version 0.15, I noticed that when downloading it and running locally the transcription is more accurate, than using WebSockets to pass the audio and running it through the docker container. Why does this happen? Is it because of websockets or the image itself?

**Comment by nshmyrev** [comment]
It is hard to guess, actually results must be identical

**Comment by Deuos** [comment]
Ok, redid tests using the official test16k.wav, the results were identical, the issue may have been with my audio examples for some reason. 
One question, the sample rate must be 16000 right? And the bit rate doesn't matter correct?

**Comment by Deuos** [comment]
Ok thank you, that examples it.
