### ISSUE TITLE
Vosk_ari not working

### ISSUE THREAD

**Issue by amosbah** [alphacep/vosk-server#237]
Hello, 

Last code for asterisk ari application is not working (code that create a new channel object for each new call). rtp_handler method is not being called for rtp packets. I assume it may be an issue with asyncio. I tried many snippets from other examples/docs without lack. Am using pyhhon 3.9.

Anyone got this annd/or fixed it?

**Comment by nshmyrev** [comment]
It works for me here. Most likely you have issue with ipv6 mapped to localhost, you need to use ipv4, replace externalmedia host with 127.0.0.1 probably.

**Comment by amosbah** [comment]
thanks a lot @nshmyrev you really saved me. It worked with the change from localhost to 127.0.0.1.

**Comment by icegas** [comment]
I'm facing same problem. 
Python 3.10.14
asterisk 18
asyncari=0.10.8
anyio=3.7.1
aioudp=0.1.1

Which versions have you used?

**Comment by icegas** [comment]
line 47: channel.answer(), why not waited ?

**Comment by nshmyrev** [comment]
@icegas you'd better file a separate issue and provide more details.
