### ISSUE TITLE
as i increases number of parallel request time taken to complete request is also increases

### ISSUE THREAD

**Issue by bbvachhani** [alphacep/vosk-server#26]
I am using 8 core Linux box, with 12 GB RAM.
I have given a 43 sec long audio file for decoding using below command:

time python3 test.py x.wav which to took ~47 sec to finished decoding

time python3 test.py x.wav & time python3 test.py x.wav which took ~56 sec to finished decoding 

time python3 test.py x.wav & time python3 test.py x.wav & time python3 test.py x.wav which took ~65 sec to finished decoding 

How many parallel connection server will handle without delayed output.

**Comment by nshmyrev** [comment]
Which model are you trying.

**Comment by bbvachhani** [comment]
kaldi-en-us-aspire

**Comment by nshmyrev** [comment]
Ok, what is the cpu on your server.

Also share the audio file.

**Comment by bbvachhani** [comment]
Hi Nicolay,

cpu info : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

I run the test again with different file (which is attached) of same length 43 sec, below are some numbers for the same:

1 audio decoding took ~23 sec to finished decoding
2 parrallel audio decoding took ~27 sec to finished decoding
3 parrallel audio decoding took ~29 sec to finished decoding
4 parrallel audio decoding took ~38 sec to finished decoding

[1to10-5times.zip](https://github.com/alphacep/kaldi-websocket-python/files/4014091/1to10-5times.zip)

**Comment by nshmyrev** [comment]
Ok, what is the cpu load during processing, what is the top output?

Did you compile the server yourself or what?

**Comment by bbvachhani** [comment]
I am running docker which is build using Dockerfile.kaldi-en.

HTOP output for one request: 
![image](https://user-images.githubusercontent.com/16445495/71651837-b2dcd900-2d46-11ea-9c79-398a72e7e2cf.png)

HTOP output for three request: 
![image](https://user-images.githubusercontent.com/16445495/71652132-2ed82080-2d49-11ea-8c30-d5b8bcc5d4a7.png)

**Comment by nshmyrev** [comment]
Ok, I think thats about the capability of your server to process 4 streams in realtime. The cache access might be the bottleneck, on i7 I process about 20 streams in realtime with en-us model.

En-us model is pretty heavy actually. Optimization direction might include training of the smaller model, tuning the beams as well as algorithmic improvement for faster processing.

**Comment by phamtan11** [comment]
hi @nshmyrev 
I run the test again like @bbvachhani  and get the same result.
my cpu info: Intel® Core™ i7-9700K CPU @ 3.60GHz × 8
i think my computer can serve 8 streams in realtime. but it not
can you show me how to detect process number streamming realtime.

**Comment by nshmyrev** [comment]
@phamtan11 ok, and what are the numbers? If you run 8 streams in parallel? What is the CPU load during that? Take a long file x.wav and run like this:

```
time python3 test.py x.wav & time python3 test.py x.wav & time python3 test.py x.wav &  time python3 test.py x.wav & time python3 test.py x.wav & time python3 test.py x.wav & time python3 test.py x.wav & time python3 test.py x.wav & time python3 test.py x.wav
```
and provide the output.

**Comment by nshmyrev** [comment]
Feel free to reopen if you have more information

**Comment by v-yunbin** [comment]
> I am running docker which is build using Dockerfile.kaldi-en.
> 
> HTOP output for one request:
> ![image](https://user-images.githubusercontent.com/16445495/71651837-b2dcd900-2d46-11ea-9c79-398a72e7e2cf.png)
> 
> HTOP output for three request:
> ![image](https://user-images.githubusercontent.com/16445495/71652132-2ed82080-2d49-11ea-8c30-d5b8bcc5d4a7.png)

dou u start many asr server？

**Comment by nshmyrev** [comment]
> dou u start many asr server？

Those are just threads, not servers
