### ISSUE TITLE
GPU server - segmentation fault

### ISSUE THREAD

**Issue by thiagopollachini** [alphacep/vosk-server#260]
After compiling with GPU support, the main model (vosk-model-en-us-0.22) works.
But when i put small and lgraph: segmentation fault.

server.py

#!/usr/bin/env python3

import json
import os
import sys
import asyncio
import pathlib
import websockets
import logging
import argparse

from vosk import BatchModel, BatchRecognizer, GpuInit

async def recognize(websocket, path):
    global args
    global pool
    global model

    rec = None
    sample_rate = args.sample_rate

    logging.info(f'Connection from {websocket.remote_address}')

    while True:

        message = await websocket.recv()

        # Load configuration if provided
        if isinstance(message, str) and 'config' in message:
            jobj = json.loads(message)['config']
            logging.info("Config %s", jobj)
            if 'sample_rate' in jobj:
                sample_rate = float(jobj['sample_rate'])
            continue

        # Create the recognizer, word list is temporary disabled since not every model supports it
        if not rec:
            rec = BatchRecognizer(model, sample_rate)

        if message == '{"eof" : 1}':
            rec.FinishStream()
            break

        if isinstance(message, str) and 'config' in message:
            continue

        rec.AcceptWaveform(message)

        while rec.GetPendingChunks() > 0:
            await asyncio.sleep(0.1)

        res = rec.Result()
        if len(res) == 0:
            await websocket.send('{ "partial" : "" }')
        else:
            await websocket.send(res)

    while rec.GetPendingChunks() > 0:
        await asyncio.sleep(0.1)

    res = rec.Result()
    await websocket.send(res)

async def start():

    global model
    global args

    # Enable logging if needed
    #
    # logger = logging.getLogger('websockets')
    # logger.setLevel(logging.INFO)
    # logger.addHandler(logging.StreamHandler())
    logging.basicConfig(level=logging.INFO)

    # Argument parser for command-line arguments
    parser = argparse.ArgumentParser(description="ASR Server with GPU support")
    parser.add_argument('--model', type=str, default=os.environ.get('VOSK_MODEL_PATH', 'model'),
                        help='Path to the model')
    parser.add_argument('--port', type=int, default=int(os.environ.get('VOSK_SERVER_PORT', 2700)),
                        help='Port to run the server on')
    parser.add_argument('--sample_rate', type=float, default=float(os.environ.get('VOSK_SAMPLE_RATE', 8000)),
                        help='Sample rate of the audio')
    parser.add_argument('--interface', type=str, default=os.environ.get('VOSK_SERVER_INTERFACE', '0.0.0.0'),
                        help='Interface to bind the server to')

    args = parser.parse_args()

    GpuInit()

    model = BatchModel(args.model)

    async with websockets.serve(recognize, args.interface, args.port):
        await asyncio.Future()

if __name__ == '__main__':
    asyncio.run(start())

gdb backtrace:

LOG ([5.5.1094~4-2b69ae]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff3784ac1 in kaldi::cuda_decoder::CudaFst::CudaFst(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, kaldi::TransitionInformation const*) ()
   from /usr/local/lib/python3.9/dist-packages/vosk-0.3.50-py3.9.egg/vosk/libvosk.so
(gdb) backtrace
#0  0x00007ffff3784ac1 in kaldi::cuda_decoder::CudaFst::CudaFst(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, kaldi::TransitionInformation const*) ()
   from /usr/local/lib/python3.9/dist-packages/vosk-0.3.50-py3.9.egg/vosk/libvosk.so
#1  0x00007ffff3757b66 in kaldi::cuda_decoder::BatchedThreadedNnet3CudaOnlinePipeline::AllocateAndInitializeData(fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&) ()
   from /usr/local/lib/python3.9/dist-packages/vosk-0.3.50-py3.9.egg/vosk/libvosk.so
#2  0x00007ffff37544d0 in kaldi::cuda_decoder::BatchedThreadedNnet3CudaOnlinePipeline::BatchedThreadedNnet3CudaOnlinePipeline(kaldi::cuda_decoder::BatchedThreadedNnet3CudaOnlinePipelineConfig const&, kaldi::OnlineNnet2FeaturePipelineInfo&, fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > const&, kaldi::nnet3::AmNnetSimple const&, kaldi::TransitionModel const&) () from /usr/local/lib/python3.9/dist-packages/vosk-0.3.50-py3.9.egg/vosk/libvosk.so
#3  0x00007ffff3751686 in BatchModel::BatchModel(char const*) () from /usr/local/lib/python3.9/dist-packages/vosk-0.3.50-py3.9.egg/vosk/libvosk.so
#4  0x00007ffff37261b2 in vosk_batch_model_new () from /usr/local/lib/python3.9/dist-packages/vosk-0.3.50-py3.9.egg/vosk/libvosk.so
#5  0x00007ffff6a87052 in ffi_call_unix64 () from /usr/local/lib/python3.9/dist-packages/_cffi_backend.cpython-39-x86_64-linux-gnu.so
#6  0x00007ffff6a8544c in ffi_call_int () from /usr/local/lib/python3.9/dist-packages/_cffi_backend.cpython-39-x86_64-linux-gnu.so
#7  0x00007ffff6a834bf in cdata_call (cd=0x7ffff6a433c0, args=<optimized out>, kwds=<optimized out>) at src/c/_cffi_backend.c:3229
#8  0x000000000051d89b in _PyObject_MakeTpCall ()
#9  0x00000000005175ba in _PyEval_EvalFrameDefault ()
#10 0x00000000005106ed in ?? ()
#11 0x0000000000528d21 in _PyFunction_Vectorcall ()
#12 0x0000000000537b80 in ?? ()
#13 0x000000000051d6f5 in _PyObject_MakeTpCall ()
#14 0x00000000005170e4 in _PyEval_EvalFrameDefault ()
#15 0x000000000054c00a in ?? ()
#16 0x00007ffff77ef11f in ?? () from /usr/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so

**Comment by nshmyrev** [comment]
GPU server doesn't support lgraphs

**Comment by thiagopollachini** [comment]
> GPU server doesn't support lgraphs

Thank you.
