### ISSUE TITLE
GPU + small model

### ISSUE THREAD

**Issue by thiagopollachini** [alphacep/vosk-server#261]
When i load a small model, vosk + GPU doesn't work.

ERROR: SymbolTable::ReadText: Can't open file: /opt/vosk-models/vosk-model-small-en-us-0.15/graph/words.txt
ERROR ([5.5.1094~4-2b69ae]:BatchModel():batch_model.cc:58) Could not read symbol table from file /opt/vosk-models/vosk-model-small-en-us-0.15/graph/words.txt

The main model works fine.
Can anyone point me to the right direction?

Thanks

**Comment by nshmyrev** [comment]
Same as https://github.com/alphacep/vosk-server/issues/260
