### ISSUE TITLE
Any way to include output of kaldi unsupervised diarization in response?

### ISSUE THREAD

**Issue by Anfa-am** [alphacep/vosk-server#33]

**Comment by nshmyrev** [comment]
Maybe not diarization but just speaker id? This feature is planned, but not implemented yet.

**Comment by Anfa-am** [comment]
Speaker ID sounds sufficient. What implementation did you have in mind, what would be involved? I'd love to contribute.

**Comment by nshmyrev** [comment]
I have added basic speakerid support to vosk-api recently in https://github.com/alphacep/vosk-api/commit/aa91ccf68bdb6a8db5172456692066135692bc41, you are welcome to test and provide your feeback.

**Comment by nshmyrev** [comment]
Feel free to reopen if needed.

**Comment by milind-soni** [comment]
how is it different from diarization and how do I test it? @nshmyrev
