### ISSUE TITLE
Docker doesn't work on Ivy Bridge without AVX2

### ISSUE THREAD

**Issue by kernelpanic700** [alphacep/vosk-server#34]
Greetings!

I'm trying to run docker container as said in README:
# docker run -p 2700:2700 alphacep/kaldi-ru:latest
vosk --min-active=200 --max-active=3000 --beam=10.0 --lattice-beam=2.0 --acoustic-scale=1.0 --frame-subsampling-factor=3 --endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10 --endpoint.rule2.min-trailing-silence=0.5 --endpoint.rule3.min-trailing-silence=1.0 --endpoint.rule4.min-trailing-silence=2.0
LOG (vosk[5.5.600~1-70c3b]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
but it doesn't work..

If I run container and enter into it (docker run -i -t f9b2486789ea /bin/bash )
and type this:
# python3 ./asr_server.py /opt/kaldi-ru/model/
vosk --min-active=200 --max-active=3000 --beam=10.0 --lattice-beam=2.0 --acoustic-scale=1.0 --frame-subsampling-factor=3 --endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10 --endpoint.rule2.min-trailing-silence=0.5 --endpoint.rule3.min-trailing-silence=1.0 --endpoint.rule4.min-trailing-silence=2.0
LOG (vosk[5.5.600~1-70c3b]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
Illegal instruction (core dumped)
I get a similar error. 
Output of "valgrind python3 asr_server.py >& crash.log" :
[crash.log.gz](https://github.com/alphacep/vosk-server/files/4237244/crash.log.gz)

OSes Debian 9 and 10, the same error.
What I do wrong? What I'm missing?

**Comment by nshmyrev** [comment]
What is your CPU? Maybe it is very old, the default docker is built with AVX2 I think.

**Comment by kernelpanic700** [comment]
Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS)

**Comment by nshmyrev** [comment]
Ok, that one is pretty old. 

You can probably simply install vosk via pip, pip version is built for Nehalem, so should work on your CPU. The server will work too. Then you can clone and run the server yourself.

I am not sure we want to rebuild docker for older CPUs.

**Comment by kernelpanic700** [comment]
Thank you for help, I'll try it.

**Comment by nshmyrev** [comment]
Should be fixed now, I uploaded new images.
