### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by morfeusys** [alphacep/vosk-server#39]
Hi @nshmyrev ! I'm trying now to create a Heroku buttons for fast deploying of ready to use Vosk server Docker images. [Here](https://github.com/just-ai/vosk-asr-server) you can find them (russian model can be evaluated now).

But right after deploying Heroku fails to start server with error message

```
vosk --min-active=200 --max-active=3000 --beam=10.0 --lattice-beam=2.0 --acoustic-scale=1.0 --frame-subsampling-factor=3 --endpoint.silence-phones=1:2:3:4:5:6:7:8:9:10 --endpoint.rule2.min-trailing-silence=0.5 --endpoint.rule3.min-trailing-silence=1.0 --endpoint.rule4.min-trailing-silence=2.0 
LOG (vosk[5.5.600~1-70c3b]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
Illegal instruction
```

Are there any thoughts about why it may appear?
Thank you.

**Comment by nshmyrev** [comment]
Probably same issue as #34, I might update docker to support older cpus

**Comment by nshmyrev** [comment]
I learned a bit more on Heroku and honestly I don't think it is the right platform to deploy something like the ASR server. The CPU types are too lightweight and the virtualization is too hidden. Maybe performance-m dyno can run fine, I'm not sure.

I don't think the economy would work. It is probably better to run a pack on AWS, c5.4xlarge work well.

**Comment by morfeusys** [comment]
Thanks! Going to lookup the way to one click deployment solution for AWS
