### ISSUE TITLE
Changing Model files on the server

### ISSUE THREAD

**Issue by yondu22** [alphacep/vosk-server#43]
What is your suggestion on changing the model on the server with the least disturbance
For example if my model is in /opt/model/
and i change the files in it and load a new model, how should I let the asr_server.py reload this model without needing to restart the python script or the docker?

**Comment by nshmyrev** [comment]
Should be no big issue but requires some code and experiments. [Here](https://github.com/alphacep/vosk-server/blob/ac74a83f36e81c4133b3fd2e60796e36e98805e8/websocket/asr_server.py#L50):

        # Create the recognizer, word list is temporary disabled since not every model supports it
        if not rec:
            if False and word_list:
                 rec = KaldiRecognizer(model, sample_rate, word_list)
            else:
                 rec = KaldiRecognizer(model, sample_rate)

Add 

       if model_updated():
             model = Model("updated path")
             rec = KaldiRecognizer(model, sample_rate)
          
There could be some memory issues keeping the old model around though, will need a proper reference counting.

**Comment by yondu22** [comment]
Is this called on every request
```
     # Create the recognizer, word list is temporary disabled since not every model supports it
        if not rec:
            if False and word_list:
                 rec = KaldiRecognizer(model, sample_rate, word_list)
            else:
                 rec = KaldiRecognizer(model, sample_rate)
```
If it is, then if i don't change the server path, just replace the graph files, then it should do it automatically without any code change?

**Comment by yondu22** [comment]
Thank you, tested and works
