### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ryuzakinho** [alphacep/vosk-server#44]
Hi, thanks a lot for your awesome tool.

I have just started using the vosk server. It works very well especially given that it can handle multiple parallel transcriptions.

I have noticed that the memory consumption of the vosk-server container continuously increases over time thus, indicating a possible memory leak.

My original RAM consumption jumped from 2.8GB to 4.6GB after a couple hundred requests. 

Any recommendation regarding this?

**Comment by madkote** [comment]
@ryuzakinho python?

**Comment by ryuzakinho** [comment]
Hi, yes I am using the `asr_server.py` and the `test.py` client.

**Comment by nshmyrev** [comment]
Let me try to reproduce this issue.

**Comment by madkote** [comment]
@ryuzakinho @nshmyrev I can only confrm, that I have similar kaldi behaviour (eating memory) also with other implementation.

**Comment by nshmyrev** [comment]
I'm sorry, I can't seem to reproduce it. 

1) Do you run vosk-server with a docker like you wrote before or directly?
2) Can you try with our default English model first, do you see the leak too?
3) How exactly do you run the clients? In parallel or one by one? Do you process the same file or  different fiels?

**Comment by nshmyrev** [comment]
This English model http://alphacephei.com/kaldi/kaldi-en-us-aspire-0.1.tar.gz

**Comment by nshmyrev** [comment]
I see the issue inside the docker probably, are you running inside a container?

**Comment by nshmyrev** [comment]
Also, do you see any bad messages in server output?

**Comment by ryuzakinho** [comment]
@nshmyrev Yes, I am running inside a container. I have also no error logs except 3 logs relating to my interrupting the audio stream: `websockets.exceptions.ConnectionClosed`.

I will try with the english model.

**Comment by ryuzakinho** [comment]
I have tried running the following command: `docker run -d -p 2700:2700 alphacep/kaldi-en:latest` and faced the same memory growth behaviour. Please find below some screenshots of the container's memory consumption originally and after sending 10 requests with the test.wav file that comes with the repository.

BEFORE: 
![image](https://user-images.githubusercontent.com/7477033/80125179-0004e500-859a-11ea-9d57-11e8ffaa3e93.png)

AFTER sending 10 requests with the test client:
![image](https://user-images.githubusercontent.com/7477033/80125291-2591ee80-859a-11ea-8889-1cec075b5a46.png)

**Comment by nshmyrev** [comment]
@ryuzakinho I don't think it is memory leak. Recognizers are allocated dynamically on connection and garbage-collected after some time, not immediately. This is simply how the server works.

It might be great to restrict number of connections one day but for now it is ok, no worries. Moreover you have spare 500Gb of memory ;)

**Comment by ryuzakinho** [comment]
Thanks for you reply and for your time and for developing this awesome project.

I have tried again by limiting the allowed the container RAM to 5GB. One thing I noticed is that the `alphacep/kaldi-en:latest` image consumes memory very fast and the container gets killed after some requests (non-parallel requests). I believe that it still runs on an older version of the vosk-api as the `vosk.i` file in the container is still matching an older version.

The container with my own models is based on the version 0.35 of the vosk-api and seems better at memory consumption. It takes much more requests to get to the container limit. The first requests consume memory quickly then, the consumption increase slows down. I have also tried an 8GB limit with my own models and was not able to notice any reduction in the amount of memory consumed even over time. 

Of course, in my case, I am testing it in a research environment with a large amount of RAM. In practice though, I do believe that such a behaviour can be a limiting factor as one needs to restart the container regularly to avoid the out of memory issue and be able to run it in a more affordable machine. For example, someone's own laptop. 

Any ideas as to parts of the program one could tinker with to deal with this?

**Comment by nshmyrev** [comment]
> Any ideas as to parts of the program one could tinker with to deal with this?

You have provide me the clear and exact instructions to reproduce your issue. I can not reproduce the behavior you see. How do you run the container? How exactly do you run the clients? Which audio do you use?

**Comment by madkote** [comment]
@nshmyrev here is an example:
* load x times model
* create  x-times decoder
* perform x times decodings on on each decoder
* trigger gc
* measure memory at each step

**Comment by nshmyrev** [comment]
@madkote I'm doing that and checking with valgrind, there are no memory issues.

**Comment by madkote** [comment]
@nshmyrev ok. this is good - I still have some mem issues. this is for sure from ctypes.

**Comment by ryuzakinho** [comment]
Here is one way I get the issue. Please note that the Docker file I used to build the image is the one that comes in vosk-server/docker:

- ` docker build --no-cache --file Dockerfile.kaldi-en --tag kaldi-en-vosk:latest .`
- `docker run --memory 5g --memory-swap 5g -d -p 2700:2700 kaldi-en-vosk:latest`

This is what I get when I run docker stats before sending any requests:
![image](https://user-images.githubusercontent.com/7477033/80214069-db187c80-8642-11ea-82cc-9937da620f31.png)

Then, I run a request (I use only utilities that were provided): 
```
 vosk-server/websocket/test.py vosk-server/websocket/test.wav
````
Here is the new RAM state after 1 request:
![image](https://user-images.githubusercontent.com/7477033/80214125-f1bed380-8642-11ea-9090-2ed33906920f.png)

After 2 requests:
![image](https://user-images.githubusercontent.com/7477033/80214153-03a07680-8643-11ea-8983-dc58dc4ff0da.png)

After 5 requests:
![image](https://user-images.githubusercontent.com/7477033/80214299-42363100-8643-11ea-9a96-9de28c03beff.png)

After 20 requests:
![image](https://user-images.githubusercontent.com/7477033/80214435-7f022800-8643-11ea-9a39-8ae49d7c8983.png)

After 50 requests
![image](https://user-images.githubusercontent.com/7477033/80214544-b2dd4d80-8643-11ea-9807-460fb90148f9.png)

After 75 requests:
![image](https://user-images.githubusercontent.com/7477033/80215065-86760100-8644-11ea-846a-3ceb6b56fbcb.png)

After 100 requests:
![image](https://user-images.githubusercontent.com/7477033/80215163-ae656480-8644-11ea-8fb5-303949ab6f37.png)

After 300 requests:
![image](https://user-images.githubusercontent.com/7477033/80215501-39def580-8645-11ea-9785-2d82c9ff7c90.png)

After 500 requests:
![image](https://user-images.githubusercontent.com/7477033/80215750-a35f0400-8645-11ea-96cf-a9869b8e58c6.png)

As you can see, the memory consumption jumps drastically. In other experiments, I am using some longer files and the increase in RAM consumption happens faster.

**Comment by nshmyrev** [comment]
> This is what I get when I run docker stats before sending any requests:

Docker stats are pretty inaccurate since there are many bugs in memory cgroups. On my Debian it simply shows 0. Can you just check top output on the host? It should stay around 2Gb for python3 process.

**Comment by ryuzakinho** [comment]
Thanks for your reply. I have repeated the experiment to look at the top output. This is what I get (please note that in the research environment I am using, I have 491GB of RAM):

Just after starting the container:
![image](https://user-images.githubusercontent.com/7477033/80285485-062bca80-872e-11ea-9dce-789f6e3c493a.png)

After 50 requests:
![image](https://user-images.githubusercontent.com/7477033/80285528-5571fb00-872e-11ea-9597-db73a2151b95.png)

After 150 requests
![image](https://user-images.githubusercontent.com/7477033/80285578-b13c8400-872e-11ea-84af-a88ffae5d115.png)

Also please note that when limiting the RAM of my container to 4GB of RAM, the container crashes after around 300 requests as indicated by the previous message I sent.

**Comment by nshmyrev** [comment]
How do you run those 300 requests? From command line one by one? I don't believe so, any other way you are using?

**Comment by ryuzakinho** [comment]
I was sending requests using this command:

```
vosk-server/websocket/test.py vosk-server/websocket/test.wav > out &
```
I actually did send the requests manually to make sure that it is not a problem related to multiple requests. I started by sending requests by batches of 10 (by quickly running the command 10 times and waiting for them to complete). Then, when my container got close to its memory limit, I started sending requests one by one until it crashed.

**Comment by nshmyrev** [comment]
Wowy, you are typing pretty fast ;)

Can you try this:

`for i in {1..300}; do vosk-server/websocket/test.py vosk-server/websocket/test.wav; done`

Does the memory grow?

**Comment by ryuzakinho** [comment]
@nshmyrev  as I already mentioned, I find the vosk-server very useful and I am super happy that I am able to test it and hats off to you for putting the time and effort into maintaining it. 

I am not that fast at typing, I was just using the upper arrow and enter very quickly. The command has the ampersand & thus, running in the background.

I have ran the command you recommended. Please find the `docker stats` output recorded below (I had to put the video in a zip file):
[user@gpu0_2020-04-26 12-47-34_converted.zip](https://github.com/alphacep/vosk-server/files/4535116/user%40gpu0_2020-04-26.12-47-34_converted.zip)

The final memory output is 3.69GB/4GB when it originally was close to 1.683GB/4GB

Then, I ran batches of 10 requests using the following command: `for i in {1..10}; do vosk-server/websocket/test.py vosk-server/websocket/test.wav > out_${i} & done`. I was waiting for all the transcriptions to complete every time. In other words, I run 10, I wait for them to finish then, 10 more etc. When running the 10th call to the command, the container reached the 4GB limit and was killed. Please find the recording of the `docker stats` below:

[user@gpu0_2020-04-26 13-07-17_converted.zip](https://github.com/alphacep/vosk-server/files/4535136/user%40gpu0_2020-04-26.13-07-17_converted.zip)

**Comment by nshmyrev** [comment]
> @nshmyrev as I already mentioned, I find the vosk-server very useful and I am super happy that I am able to test it and hats off to you for putting the time and effort into maintaining it.

great, than you!

> I have ran the command you recommended. Please find the docker stats output recorded below (I had to put the video in a zip file): user@gpu0_2020-04-26 12-47-34_converted.zip

Please make me the video with "top" output on host instead.

**Comment by nshmyrev** [comment]
Also, do you have a smaller server to try to reproduce this issue?

Last, if you run without memory limits, to what size does the memory grow if you run many requests?

**Comment by nshmyrev** [comment]
Last last, can you try to add 
```
import gc
gc.set_threshold(0)
```
to the beginning of the asr_server.py inside the container?

**Comment by ryuzakinho** [comment]
Hi @nshmyrev . I have some updates on the memory problem. I have used your latest `alphacep/kaldi-en` on another machine with 32GB of RAM. I did not face the same memory problems:
- I originally had a usage of 3.045 GB which went up to only 3.785GiB of RAM usage after 300 requests. The good thing is that the memory consumption remained stable for a long time. 

However, I am still facing the same memory problem on the original machine. I tested again on a 3rd machine and faced again memory issues. Any tips to understand the problem behind this?

**Comment by nshmyrev** [comment]
I wrote you the tips above - disable python gc.

**Comment by ryuzakinho** [comment]
@nshmyrev do I understand that the right way to do it is to add a `COPY asr_server.py /opt/vosk-server/websocket` to the `Dockerfile.kaldi-en` and build from it? The asr_server.py version would be the one with the python gc disabled?

**Comment by ryuzakinho** [comment]
@nshmyrev I have run the experiments by setting 
```
import gc
gc.set_threshold(0)
```

I built an image using Dockerfile.kaldi-en to which I added:
`COPY asr_server.py /opt/vosk-server/websocket` where asr_server.py is the asr_server script which has the gc threshold set to 0.

The results are as follows:
- In my 32GB RAM machine, the memory consumption is very good. It does not grow out of hand.
- In my original machine, I am still getting the memory problems.

Please note that for both machines, I am running Cent OS 7 with Docker version 19.03.5.

**Comment by nshmyrev** [comment]
> In my original machine, I am still getting the memory problems.

Try to run without docker on big machine and check if memory grows. If not, its most likely cgroups configuration issue.

**Comment by eugeneRover** [comment]
I ve got the same problem (Debian10/Docker/Russian model).
Downloaded fresh docker image, and uncommented gc.set_threshold(0), with no effect.

Did you came to solution of the problem ?
Would you please recommend what to tune in cgroups ?

**Comment by nshmyrev** [comment]
> I ve got the same problem (Debian10/Docker/Russian model).

How much memory does it use (oh host machine, not inside docker) and after how many requests.

**Comment by eugeneRover** [comment]
[testing.txt](https://github.com/alphacep/vosk-server/files/4736485/testing.txt)
I did some testing. 
Read text from [some news site](https://sportrbc.ru/news/5eda2a939a794725cfb1fbdb?ruid=UET9A17Z9F93cLaIAwOUAg==&from=from_main) and recorded memory consumption after each sentence.
I attached the file. Numbers are megabytes of memory on host (not in docker), as seen in htop  output (RES column). Values are stable, and do not change with time.

I send voice from modified python websocket client - '{"eof" : 1}' is sent at the end, and connection is closed too.
sample_rate is 16000.

And thank you again for your work, and for fast answer

**Comment by nshmyrev** [comment]
> And thank you again for your work, and for fast answer

You are welcome. In the testing.txt I don't see any problem, memory could jump +- 200 Mb, does it ever grow above 3Gb if you process long files?

**Comment by eugeneRover** [comment]
I'll try this tomorrow, and reply with results

**Comment by eugeneRover** [comment]
![8](https://user-images.githubusercontent.com/2088056/83935116-aed34c80-a7f9-11ea-99a5-38364b36cc88.png)

Yes, it is possible to exceed 3G of memory. 
I read about 80 sentences, each one in separate websocket session.

Also, I looked into code and tried some things but without success:
* Memory leaks on python side - tried tracemalloc,  pympler, and gc. They all show there are no leaks in python part of server. One thing here - I disabled websocket compression with `compression=None`
* Browsed swig bindings, and tried to call destructor (in [asr_server.py]:(https://github.com/alphacep/vosk-server/blob/master/websocket/asr_server.py#L80) after while cycle)
```
KaldiRecognizer.__swig_destroy__(rec)
vosk._vosk.delete_KaldiRecognizer(rec)
del rec 
```
No luck again
* Currently,  I've got  no ideas to propose. Maybe, we should call [KaldiRecognizer::CleanUp](https://github.com/alphacep/vosk-api/blob/master/src/kaldi_recognizer.cc#L160) after EOF received, and before destruction of recognizer ?

**Comment by nshmyrev** [comment]
> I send voice from modified python websocket client - '{"eof" : 1}' is sent at the end, and connection is closed too.

please share your client modifications.

**Comment by nshmyrev** [comment]
Also, what is your host OS, docker version.

**Comment by nshmyrev** [comment]
Related https://stackoverflow.com/questions/15455048/releasing-memory-in-python

**Comment by eugeneRover** [comment]
Client - https://gist.github.com/eugeneRover/e0af283ae30789aefe730f87e39bc4bb

OS Debian 10.1
Linux zzzzz 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux

$ docker version
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.11.6
 Git commit:        4c52b90
 Built:             Tue, 03 Sep 2019 19:59:35 +0200
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.6
  Git commit:       4c52b90
  Built:            Tue Sep  3 17:59:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by jassem123** [comment]
> I ve got the same problem (Debian10/Docker/Russian model).
> Downloaded fresh docker image, and uncommented gc.set_threshold(0), with no effect.
> 
> Did you came to solution of the problem ?
> Would you please recommend what to tune in cgroups ?

Same here , Am running ubuntu 18.04 with 8Gb RAM

**Comment by nshmyrev** [comment]
This should improve now with https://github.com/alphacep/vosk-server/commit/14daebd236ea16f3ec2850c7b2978bf41b23db23
