### ISSUE TITLE
Server fails moments after starting.

### ISSUE THREAD

**Issue by ifeatu** [alphacep/vosk-server#45]
docker run -d -p 2700:2700 alphacep/kaldi-en:latest

When I run this docker container it fails moments after starting...docker logs produces:

```
docker logs d1d2f2742e8a4a52f3937aff26b2c7628829e313cede5ad60cb4424c897a53c3
LOG ([5.5.643~1-7e185]:ConfigureV2():src/model.cc:138) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG ([5.5.643~1-7e185]:ConfigureV2():src/model.cc:141) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG ([5.5.643~1-7e185]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.5.643~1-7e185]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG ([5.5.643~1-7e185]:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG ([5.5.643~1-7e185]:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG ([5.5.643~1-7e185]:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG ([5.5.643~1-7e185]:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00747085 seconds in looped compilation.
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:190) Loading HCLG from /opt/vosk-model-en/model/graph/HCLG.fst
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:209) Loading words from /opt/vosk-model-en/model/graph/words.txt
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:217) Loading winfo /opt/vosk-model-en/model/graph/phones/word_boundary.int
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:225) Loading CARPA model from /opt/vosk-model-en/model/rescore/G.carpa
```

**Comment by nshmyrev** [comment]
What is your hardware please? CPU?

**Comment by ifeatu** [comment]
2020 Mac i9

**Comment by nshmyrev** [comment]
Does kald-en-atom work for you?

docker run -d -p 2700:2700 alphacep/kaldi-en-atom:latest

**Comment by ifeatu** [comment]
Nope. It fails even faster, stays up for about 5 seconds then fails.

**Comment by nshmyrev** [comment]
Ok, and what happens if you run the server inside the docker manually like this:

```
shmyrev@api:~$ sudo docker run -it -p 2700:2700 alphacep/kaldi-en:latest /bin/bash
root@a9e0db45a54b:/opt/vosk-server/websocket# python3 ./asr_server.py /opt/vosk-model-en/model
LOG ([5.5.643~1-7e185]:ConfigureV2():src/model.cc:138) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG ([5.5.643~1-7e185]:ConfigureV2():src/model.cc:141) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG ([5.5.643~1-7e185]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.5.643~1-7e185]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG ([5.5.643~1-7e185]:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG ([5.5.643~1-7e185]:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG ([5.5.643~1-7e185]:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG ([5.5.643~1-7e185]:CompileLooped():nnet-compile-looped.cc:345) Spent 0.0060811 seconds in looped compilation.
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:190) Loading HCLG from /opt/vosk-model-en/model/graph/HCLG.fst
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:209) Loading words from /opt/vosk-model-en/model/graph/words.txt
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:217) Loading winfo /opt/vosk-model-en/model/graph/phones/word_boundary.int
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:225) Loading CARPA model from /opt/vosk-model-en/model/rescore/G.carpa
```

**Comment by ifeatu** [comment]
Dies.  Ends with "killed"

`root@4e255f2b2ad9:/opt/vosk-server/websocket# python3 ./asr_server.py /opt/vosk-model-en/model
LOG ([5.5.643~1-7e185]:ConfigureV2():src/model.cc:138) Decoding params beam=13 max-active=7000 lattice-beam=6
LOG ([5.5.643~1-7e185]:ConfigureV2():src/model.cc:141) Silence phones 1:2:3:4:5:6:7:8:9:10:11:12:13:14:15
LOG ([5.5.643~1-7e185]:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG ([5.5.643~1-7e185]:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG ([5.5.643~1-7e185]:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG ([5.5.643~1-7e185]:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG ([5.5.643~1-7e185]:Collapse():nnet-utils.cc:1472) Added 1 components, removed 2
LOG ([5.5.643~1-7e185]:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00634193 seconds in looped compilation.
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:190) Loading HCLG from /opt/vosk-model-en/model/graph/HCLG.fst
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:209) Loading words from /opt/vosk-model-en/model/graph/words.txt
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:217) Loading winfo /opt/vosk-model-en/model/graph/phones/word_boundary.int
LOG ([5.5.643~1-7e185]:ReadDataFiles():src/model.cc:225) Loading CARPA model from /opt/vosk-model-en/model/rescore/G.carpa
Killed`

**Comment by nshmyrev** [comment]
Most likely it goes out of memory. Do you have memory limitation in your docker? It should be something like 4Gb or better 8Gb for this server to run.

**Comment by ifeatu** [comment]
Great call!  Looks like Docker limited my memory to 2GB by default.

**Comment by nshmyrev** [comment]
Ok, let me know if you have some other issues.
