### ISSUE TITLE
Hello! I wrote client for vosk-server on golang.

### ISSUE THREAD

**Issue by NerdDoc** [alphacep/vosk-server#46]
You can add it into vosk-server examples, if you want.
Here is link - https://github.com/NerdDoc/vosk-server-go-client

**Comment by nshmyrev** [comment]
Thank you, looks cool! I would happy to include this, maybe you can submit a pull request so your submission will stay in history. Otherwise I can merge myself.

**Comment by NerdDoc** [comment]
ok, i'll create PR.

**Comment by nshmyrev** [comment]
Merged now!
