### ISSUE TITLE
offline recognize

### ISSUE THREAD

**Issue by vinnitu** [alphacep/vosk-server#50]
Hello!

It is ok. But sometimes need process recorded files.

What is the best practice recognize such data?

**Comment by nshmyrev** [comment]
I don't get your problem, sorry.

**Comment by vinnitu** [comment]
I mean in realtime we get "partial" event - but when we recognize recorded offline file we can send data to websocket as fast as can and we nead only "text" and "words" events/info

**Comment by nshmyrev** [comment]
You can simply filter out partial responses you receive and keep the text ones. You can also skip rec.PartialResult in the code.

**Comment by nshmyrev** [comment]
Let me know if you have further questions please.
