### ISSUE TITLE
speakerid

### ISSUE THREAD

**Issue by vinnitu** [alphacep/vosk-server#54]
I use speaker id feature in vosk-api, but is it possible add it to vosk-server?

**Comment by nshmyrev** [comment]
You just need to load the speaker model (I wanted to adjust constructors to make them more flexible), the change should be simple

**Comment by cdgraff** [comment]
Hi @nshmyrev I made the changes to load the Speaker model, but I don't know how to confirm if that is working? some advice?

https://github.com/mediainbox/vosk-server/commit/72ae8d5af4323dae656c4641fce2654b0f98486d

**Comment by nshmyrev** [comment]
We have recently added https://github.com/alphacep/vosk-server/blob/master/docker/Dockerfile.kaldi-en-spk, it returns speaker labels now.
