### ISSUE TITLE
uWSGI for Websocket and gRPC ?

### ISSUE THREAD

**Issue by apntt** [alphacep/vosk-server#56]
I saw you comment "Websocket and grpc servers are similar. I need to think how to run gtpc inside the docker too." 

May I suggest you to use uWSGI for websocket and gRPC. 

it's easy to configure with a simple file and robust !

Just a prosposal if you have no other lead.

**Comment by nshmyrev** [comment]
> Just a prosposal if you have no other lead.

We need to share the data object (Model) across workers, how is that implemented in uWSGI? I see only shared area, but not the objects.

**Comment by apntt** [comment]
I will investigate and come back to you.

**Comment by nshmyrev** [comment]
Feel free to reopen if you have some more information on this.

**Comment by apntt** [comment]
Unfornately not, i run many tests on uWSGI but worker can share file, like you said it but each worker load the file  (=model) in memory so obviously the memory expload very quickly depending size of model and number of worker.

Sorry i don't bring help on this...
