### ISSUE TITLE
Memory Leak (With debug steps)

### ISSUE THREAD

**Issue by GabrielBG99** [alphacep/vosk-server#62]
I tested in 3 different scenarios:
- With the docker image alphacep/kaldi-en;
- With a script in my local machine; and
- Inside Qtile WM, with a custom widget.

All tests were done using only the microphone.

**Docker**
I'm using the the same script that is provided in [test_microphone.py](https://github.com/alphacep/vosk-server/blob/master/websocket/), only changing the interpreter path

**Local**
Running in my local installation of Kaldi, using python's vosk-api.
I used the same script provided in [test_microphone.py](https://github.com/alphacep/vosk-api/blob/master/python/example/test_microphone.py), only changing the interpreter path.

**Qtile**
Is a custom script that ables me to start kaldi with a simple click in the bottom bar.
I tried to use gc right after closing the audio stream and deleting the KaldiRecognizer object but it has no effect, the RAM usage still increasing every time I stop the widget. The only way to free the memory is restarting de WM with his shortcut after stoping the recognizer

All prints and scripts:
[url](https://drive.google.com/drive/folders/16WyGMy4K9N6CvIICBJcRnjDQViUEtTle?usp=sharing)

OS: Arch Linux, kernel 5.7.4
Processor: Ryzen 5 2600
RAM: 16GB
WM: Qtile v0.15.1
Docker version: 19.03.11-ce
Docker-compose version: 1.26.0

**Comment by nshmyrev** [comment]
And what is the problem, why is there memory leak? What are the numbers?

**Comment by GabrielBG99** [comment]
## Docker:
Every time the script is closed, the memory used by the container for that connection is not released and the socket is not closed. It easily passed the 5GB used by running the script a few times.

- RAM usage before starting the container
![1](https://user-images.githubusercontent.com/43591440/85595536-54baef80-b61f-11ea-8c5c-ce1dfd30048b.png)
- RAM usage after starting the container
![2](https://user-images.githubusercontent.com/43591440/85595543-571d4980-b61f-11ea-974c-f66d42402ff3.png)
- RAM usage after running the script 2 times
![3](https://user-images.githubusercontent.com/43591440/85595547-584e7680-b61f-11ea-920c-6d58339e1752.png)
- RAM usage after running the script 3 times
![4](https://user-images.githubusercontent.com/43591440/85595555-597fa380-b61f-11ea-8a61-aaad12d0412f.png)
- RAM usage after running the script 4 times (with htop)
![5](https://user-images.githubusercontent.com/43591440/85595561-5ab0d080-b61f-11ea-8567-3fc763b737a2.png)
- RAM usage after stopping the container
![6](https://user-images.githubusercontent.com/43591440/85595565-5c7a9400-b61f-11ea-9b9a-ffe7be26eb47.png)

## Qtile:
I detailed in the issue

- RAM usage before starting the stt widget
![1](https://user-images.githubusercontent.com/43591440/85595740-7c11bc80-b61f-11ea-9e03-308334e90671.png)
- RAM usage after starting the stt widget
![2](https://user-images.githubusercontent.com/43591440/85595747-7d42e980-b61f-11ea-8126-ea117f49212d.png)
- RAM usage after stopping the stt widget
![3](https://user-images.githubusercontent.com/43591440/85595752-7e741680-b61f-11ea-9904-ac7d7f748f52.png)
~ +300MB each time I stop the widget even if I run gc.collect() after deleting the recognizer object


## Local:
It's everything fine, I just mentioned to say that the problem does not occur running the script locally.

- Before runnig the script
![1](https://user-images.githubusercontent.com/43591440/85596845-74064c80-b620-11ea-9ece-1105e18fe0e8.png)
- After runnig the script
![2](https://user-images.githubusercontent.com/43591440/85596853-75377980-b620-11ea-97f1-76b86d94487a.png)

 Scripts used are in: https://drive.google.com/drive/folders/16WyGMy4K9N6CvIICBJcRnjDQViUEtTle?usp=sharing

**Comment by nshmyrev** [comment]
In docker case it should be better as in #44 

As for qtile case, you should not create Model object for every request, you need to keep one Model per application and create just the recognizer.

**Comment by nshmyrev** [comment]
Like this:

```
--- qtile.py	2020-06-24 19:52:45.000000000 +0300
+++ qtile_fixed.py	2020-06-24 19:53:27.000000000 +0300
@@ -14,7 +14,7 @@ class STT(base.ThreadPoolText):
         self.add_defaults(STT.defaults)
         self.stop_button = stop_button
         self.stopped = True
-        self.model_path = model_path
+        self.model = Model(model_path)
         self._pyaudio = PyAudio()
 
     def poll(self):
@@ -34,7 +34,7 @@ class STT(base.ThreadPoolText):
                 return str(e)
             
             kaldi_recognizer = KaldiRecognizer(
-                Model(self.model_path), 
+                self.model, 
                 16000
             )
             while not self.stopped:
```
