### ISSUE TITLE
Can not run test

### ISSUE THREAD

**Issue by zim32** [alphacep/vosk-server#69]
I would be very suprised if something written in python works

**cannot import name 'asynccontextmanager'**

Python 3.6.9
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

**Comment by zim32** [comment]
Ok installed python 3.7 
But now I can not install pyaudio

**Comment by lordB8r** [comment]
which pip3 -V are you using?

**Comment by nshmyrev** [comment]
Feel free to reopen if you still need help. Pyaudio is easy to install if you follow the instructions carefully.
