### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by TaridaGeorge** [alphacep/vosk-server#70]
Questions:

Q1: Is this line ([L41](https://github.com/alphacep/vosk-server/blob/8e7b0ad2ed8fa4fb8483eeda10ee7c0cd3cb0bea/grpc/stt_server.py#L41)) from stt_server.py used for something?

Q2: What are the drawbacks from uncommenting `gc.set_threshold(0)` line?

Q3: Wouldn't be better to send the start_time and end_time of words in milliseconds as int64 instead of google.protobuf.Duration?

**Comment by nshmyrev** [comment]
> Q1: Is this line (L41) from stt_server.py used for something?

no

> Q2: What are the drawbacks from uncommenting gc.set_threshold(0) line?

disabling garbage collection slows down the runtime

> Q3: Wouldn't be better to send the start_time and end_time of words in milliseconds as int64 instead of google.protobuf.Duration?

no
