### ISSUE TITLE
python Asterisk library, which one?

### ISSUE THREAD

**Issue by lordB8r** [alphacep/vosk-server#71]
There are several on [PyPi](https://pypi.org/search/?q=asterisk), but it's unclear which one you are referencing in your eagi.py file.

**Comment by nshmyrev** [comment]
https://pypi.org/project/pyst2/

You'd better also check https://github.com/alphacep/vosk-asterisk

**Comment by lordB8r** [comment]
thanks for the quick response!

**Comment by lordB8r** [comment]
I don't see any requirements.txt. Would be useful for each project if that was available.

**Comment by lordB8r** [comment]
My bad, I see it in the install dependencies section. Wasn't clear to me that that was not for my remote docker server, but my local pbx. Thanks!
