### ISSUE TITLE
WebRTC sending error

### ISSUE THREAD

**Issue by tingyang01** [alphacep/vosk-server#74]
I am testing the Webrtc server version on the AWS server.
but I am getting this error on the server-side(python) and the browser is not getting any stt result.
I am very not familiar with this library.
Got frame <av.AudioFrame 0, pts=288000, 960 samples at 48000Hz, stereo, s16 at 0x7fc8f0076a58>
Sending response {
  "partial" : ""
}
Got frame <av.AudioFrame 0, pts=288960, 960 samples at 48000Hz, stereo, s16 at 0x7fc8f00dab38>
Sending response {
  "partial" : ""
}
Task exception was never retrieved
future: <Task finished coro=<RTCSctpTransport._transmit() done, defined at /home/ubuntu/kaldi_mic/lib/python3.6/site-packages/aiortc/rtcsctptransport.py:1505> exception=ConnectionError('Cannot send encrypted data, not connected',)>
Traceback (most recent call last):
  File "/home/ubuntu/kaldi_mic/lib/python3.6/site-packages/aiortc/rtcsctptransport.py", line 1539, in _transmit
    await self._send_chunk(chunk)
  File "/home/ubuntu/kaldi_mic/lib/python3.6/site-packages/aiortc/rtcsctptransport.py", line 1344, in _send_chunk
    chunk,
  File "/home/ubuntu/kaldi_mic/lib/python3.6/site-packages/aiortc/rtcdtlstransport.py", line 655, in _send_data
    raise ConnectionError("Cannot send encrypted data, not connected")
ConnectionError: Cannot send encrypted data, not connected

I am very happy if you can fix it.
Thank you.

**Comment by nshmyrev** [comment]
This thing is not yet fully tested yet, I will check soon. Thank you for the report.

**Comment by nshmyrev** [comment]
Let us know if still valid. I think it should work

**Comment by tingyang01** [comment]
Thank you, it works now.

**Comment by nshmyrev** [comment]
@tingyang01 thank you for confirmation!
