### ISSUE TITLE
asynccontextmanager

### ISSUE THREAD

**Issue by mister511** [alphacep/vosk-server#76]
[root@Kaldi websocket]# ./test_microphone.py localhost:2700
Traceback (most recent call last):
  File "./test_microphone.py", line 7, in <module>
    from contextlib import asynccontextmanager, contextmanager, AsyncExitStack
ImportError: cannot import name 'asynccontextmanager'

[root@Kaldi websocket]# pip3 install asyncio-contextmanager
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: asyncio-contextmanager in /usr/local/lib/python3.6/site-packages

what could be the problem?

**Comment by nshmyrev** [comment]
As in https://github.com/mosquito/aio-pika/issues/188 this feature was added in python 3.6.5, most likely you have older one.

Try to upgrade python.

**Comment by mister511** [comment]
[root@Kaldi asterisk-16.14.0]# python3 -V
Python 3.6.8

**Comment by hc038** [comment]
@mister511 did you solve the problem?
I am having the same problem now

**Comment by 88fingerslukee** [comment]
I'm also having this problem. help!

**Comment by nshmyrev** [comment]
> I'm also having this problem. help!

What is your distribution and python version.

**Comment by 88fingerslukee** [comment]
I messed up and tried test_microphon.py from the root of the server and not from inside the docker container. It's all sorted now.

**Comment by nshmyrev** [comment]
We moved to sounddevice, no need for contextmanager anymore
