### ISSUE TITLE
Can I use this library to do user' voiceprint identification ?

### ISSUE THREAD

**Issue by WestFarmer** [alphacep/vosk-server#79]
Thanks for create this library, I want to do some research on voiceprint based user authentication. Can you guys share some thoughts on this topic.

**Comment by nshmyrev** [comment]
Hello. We support voice auth in vosk library, in the server it is just not yet implemented:

https://github.com/alphacep/vosk-api/blob/master/python/example/test_speaker.py

**Comment by nshmyrev** [comment]
Now speaker identification is supported in the server as well in commit bcac27c28254e23b3151271bbf26066f8f10eafb
