### ISSUE TITLE
Building Dockerfile.kaldi-vosk-server fails - Missing files in /opt/kaldi/tools/OpenBLAS/install/lib/

### ISSUE THREAD

**Issue by advand** [alphacep/vosk-server#87]
Hello,

When trying to build the image using the provided build.sh, the process fails with:

```
x86_64-linux-gnu-g++: error: /opt/kaldi/tools/OpenBLAS/install/lib/liblapack.a: No such file or directory
x86_64-linux-gnu-g++: error: /opt/kaldi/tools/OpenBLAS/install/lib/libblas.a: No such file or directory
x86_64-linux-gnu-g++: error: /opt/kaldi/tools/OpenBLAS/install/lib/libf2c.a: No such file or directory
error: command 'x86_64-linux-gnu-g++' failed with exit status 1
```
This appears to happen at:
`KALDI_MKL=$KALDI_MKL KALDI_ROOT=/opt/kaldi python3 ./setup.py install --single-version-externally-managed --root=/ ` (line 55 of Dockerfile.kaldi-vosk-server)

Best,
Adrian

**Comment by nshmyrev** [comment]
Sorry, I forgot to push file updates. This should be fixed now with

https://github.com/alphacep/vosk-server/commit/2acd0b1445a9623fc2602634b7273b766160338a
