### ISSUE TITLE
 Dockerfile.vosk-unimrcp  stuck in Loading CARPA model

### ISSUE THREAD

**Issue by amolinero** [alphacep/vosk-server#92]
Hi,
update docker image from last image (alphacep/vosk-unimrcp:latest), executing:

docker run -p 1544:1544 -p 8060:8060 -p 5001-5200:5001-5200 alphacep/vosk-unimrcp

plugin is loading and stuck in this point:

LOG (VoskAPI:ReadDataFiles():src/model.cc:281) Loading CARPA model from /opt/kaldi/model/rescore/G.carpa

I am using MacOS with several resources (32GB and 2,8 GHz Intel Core i7 4 sockets), indeed opening a session to docker image and executing a 'top':

<img width="651" alt="Captura de pantalla 2021-02-03 a las 13 29 40" src="https://user-images.githubusercontent.com/3083779/106747938-d696e080-6624-11eb-9ca4-611d420af482.png">

**Comment by nshmyrev** [comment]
It is not stuck, it waits for connections from the client. It just doesn't flush the output properly.

**Comment by amolinero** [comment]
It seems is blocking unimrcp execution after plugin loading:

2021-02-03 12:23:46:129780 [INFO]   Load Plugin [Vosk-Recog-1] [/usr/local/unimrcp/plugin/voskrecog.so]
LOG (VoskAPI:RemoveOrphanNodes():nnet-nnet.cc:948) Removed 1 orphan nodes.
LOG (VoskAPI:RemoveOrphanComponents():nnet-nnet.cc:847) Removing 2 orphan components.
LOG (VoskAPI:Collapse():nnet-utils.cc:1488) Added 1 components, removed 2
LOG (VoskAPI:CompileLooped():nnet-compile-looped.cc:345) Spent 0.00561118 seconds in looped compilation.
LOG (VoskAPI:ReadDataFiles():src/model.cc:221) Loading i-vector extractor from /opt/kaldi/model/ivector/final.ie
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:183) Computing derived variables for iVector extractor
LOG (VoskAPI:ComputeDerivedVars():ivector-extractor.cc:204) Done.
LOG (VoskAPI:ReadDataFiles():src/model.cc:246) Loading HCLG from /opt/kaldi/model/graph/HCLG.fst
LOG (VoskAPI:ReadDataFiles():src/model.cc:265) Loading words from /opt/kaldi/model/graph/words.txt
LOG (VoskAPI:ReadDataFiles():src/model.cc:273) Loading winfo /opt/kaldi/model/graph/phones/word_boundary.int
LOG (VoskAPI:ReadDataFiles():src/model.cc:281) Loading CARPA model from /opt/kaldi/model/rescore/G.carpa


i mean, after plugin loading unimrcp executes more tasks, is also having problem unimrcp to flush output?

**Comment by nshmyrev** [comment]
It starts fine, it just doesn't flush the output in docker, the messages are buffered. You can run umc client and check it works.

**Comment by amolinero** [comment]
yes, it is working (some flush issue with messages):

<img width="1219" alt="Captura de pantalla 2021-02-03 a las 14 17 04" src="https://user-images.githubusercontent.com/3083779/106752478-caae1d00-662a-11eb-8a71-b49e676ea301.png">

do you have any data about performance? some mem/cpu requeriments to support X concurrent sessions?

**Comment by nshmyrev** [comment]
> some mem/cpu requeriments to support X concurrent sessions?

It supports about 20 parallel streams on 8-core intel CPU. 70 streams on more recent 32-core servers.

**Comment by amolinero** [comment]
thanks. Have you experiment to integrate with Avaya Experience Portal IVR?

**Comment by nshmyrev** [comment]
No

**Comment by amolinero** [comment]
is interesting for you? So we have that environment ready to test.

**Comment by nshmyrev** [comment]
> is interesting for you?

Sure, let me know how it goes

**Comment by amolinero** [comment]
Hi Nickolay,
we have managed to configure with Avaya EP, and MRCP communication is stablished. You can see in attached log a ping message from avaya (192.168.2.152) to UniMRCP (docker running in 192.168.2.123) is coming every 10 seconds:

2021-02-08 16:05:58:759934 [INFO]   Receive SIP Event [nua_i_options] Status 100 Trying [SIP-Agent-1]
2021-02-08 16:05:58:759991 [INFO]   Resource Discovery SDP
[v=0
o=UniMRCPServer 0 0 IN IP4 172.17.0.5 
s=-
c=IN IP4 172.17.0.5
t=0 0
m=application 0 TCP/MRCPv2 1
a=resource:speechsynth
a=resource:speechrecog
m=audio 0 RTP/AVP 0 8 96 101
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:96 L16/8000
a=rtpmap:101 telephone-event/8000
]

In log also you can find a session for a call trying to recognize, but i think we are having a problem about SDP messages in sense uniMRCP is answer with docker IP instead host ip. The UniMRCP server at 192.168.2.123 replies with an SDP that says the server RTP address is at 172.17.0.5:

o=UniMRCPServer 0 0 IN IP4 172.17.0.5 **(docker ip, not host ip)**

i have also take a look of https://github.com/unispeech/unimrcp/issues/260 similar issue and, i supposse, IP in SDP messages can be forced, but that must be done in docker compose.
any other idea?
[unimrcp.log](https://github.com/alphacep/vosk-server/files/5945385/unimrcp.log)

**Comment by nshmyrev** [comment]
> i have also take a look of unispeech/unimrcp#260 similar issue and, i supposse, IP in SDP messages can be forced, but that must be done in docker compose.

You can probably run the server without docker, I heard such complains before.

**Comment by nshmyrev** [comment]
I suppose this one is solved now
